##############################################################################
# Makefile for .net core enviroment
#
# Author: Ivan Pavic
##############################################################################


all : run

run :
	@dotnet run $(d) $(in) $(out) > /dev/null

clean :
	rm sads.exe
